[build]
  command = "npm build"
  functions = "src/functions"

[template.environment]
  FOXY_TIMEZONE = "Enter your store's timezone, such as `America/Los_Angeles`, `America/Chicago`, `America/New_York`, `Europe/Paris`, etc. You can see a complete list here: https://gist.github.com/diogocapela/12c6617fc87607d11fd62d2a4f42b02a"
  FOXY_API_CLIENT_ID = "Enter your Foxy.io API Client ID here."
  FOXY_API_CLIENT_SECRET = "Enter your Foxy.io API Client Secret here."
  FOXY_API_REFRESH_TOKEN = "Enter your Foxy.io API Refresh Token here."
